joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

torso_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - torso_lift_joint

head_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - head_1_joint
    - head_2_joint

arm_left_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint

arm_right_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint

gripper_left_left_finger_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_left_left_finger_joint
gripper_left_right_finger_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_left_right_finger_joint
gripper_right_left_finger_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_right_left_finger_joint
gripper_right_right_finger_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_right_right_finger_joint