joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

joint_trajectory_controller: 
  type: position_controllers/JointTrajectoryController  
  joints:
    - left_driver_joint