joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

leg_joint_trajectory_controller: 
  type: position_controllers/JointTrajectoryController  
  joints:
    - multirotor_x4_leg_001_joint
    - multirotor_x4_leg_002_joint

arm_joint_trajectory_controller: 
  type: position_controllers/JointTrajectoryController  
  joints:
    - shoulder_roll_structure_right_joint
    - shoulder_yaw_structure_right_joint
    - elbow_pitch_structure_right_joint
    - forearm_link_right_joint
    - shoulder_roll_structure_left_joint
    - shoulder_yaw_structure_left_joint
    - elbow_pitch_structure_left_joint
    - forearm_link_left_joint