controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - head1_joint
      - head2_joint
      - torso1_joint
      - torso2_joint
      - torso3_joint
      - torso4_joint
      - left_arm1_joint
      - left_arm2_joint
      - left_arm3_joint
      - left_arm4_joint
      - left_arm5_joint
      - left_arm6_joint
      - left_arm7_joint
      - right_arm1_joint
      - right_arm2_joint
      - right_arm3_joint
      - right_arm4_joint
      - right_arm5_joint
      - right_arm6_joint
      - right_arm7_joint

    command_interfaces:
      - position
      # - velocity
      # - effort

    state_interfaces:
      - position
      - velocity

    open_loop_control: True