joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

torso_trajectory_controller: 
  type: position_controllers/JointTrajectoryController  
  joints:
    - torso_roll
    - torso_pitch
    - torso_yaw

neck_trajectory_controller: 
  type: position_controllers/JointTrajectoryController  
  joints:
    - neck_roll
    - neck_pitch
    - neck_yaw

right_arm_trajectory_controller: 
  type: position_controllers/JointTrajectoryController  
  joints: &right_arm_joints
    - r_shoulder_pitch
    - r_shoulder_roll
    - r_shoulder_yaw
    - r_elbow
    - r_wrist_prosup
    - r_wrist_pitch
    - r_wrist_yaw

left_arm_trajectory_controller: 
  type: position_controllers/JointTrajectoryController  
  joints: &left_arm_joints
    - l_shoulder_pitch
    - l_shoulder_roll
    - l_shoulder_yaw
    - l_elbow
    - l_wrist_prosup
    - l_wrist_pitch
    - l_wrist_yaw

right_arm_velocity_controller: 
  type: velocity_controllers/JointGroupVelocityController  
  joints: *right_arm_joints

left_arm_velocity_controller: 
  type: velocity_controllers/JointGroupVelocityController  
  joints: *left_arm_joints