controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

right_arm_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint

    command_interfaces:
      - position
      - velocity
      # - effort

    state_interfaces:
      - position
      - velocity

left_arm_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint

    command_interfaces:
      - position
      - velocity
      # - effort

    state_interfaces:
      - position
      - velocity

torso_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - torso_lift_joint

    command_interfaces:
      - position
      - velocity
      # - effort

    state_interfaces:
      - position
      - velocity

head_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - head_pan_joint
      - head_tilt_joint

    command_interfaces:
      - position
      - velocity
      # - effort

    state_interfaces:
      - position
      - velocity

right_arm_velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

left_arm_velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

torso_velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - torso_lift_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

head_velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - head_pan_joint
      - head_tilt_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity